SIGEAO/Controllers/AppointmentController.cs
using SIGEAO.Models.Repositories;
using SIGEAO.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIGEAO.Controllers {
	public class AppointmentController : Controller {

		public IAppointmentRepository repository = new AppointmentRepository();

		public ActionResult Index() {
			return View("Index", new AppointmentViewModel());
		}

		[HttpPost]
		public ActionResult Create(AppointmentViewModel model) {
			try {
				repository.TrySaveAppointment(model);
				return RedirectToAction("Index");
			} catch (Exception ex) {
				ModelState.AddModelError("", "");
				return View(model);
			}
		}
	}
}

SIGEAO/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SIGEAO.Models;

namespace SIGEAO.Controllers {
  public class CategoriesController : Controller {
	private SIGEAO_Entities_EF db = new SIGEAO_Entities_EF();

	// GET: Categories
	public async Task<ActionResult> Index() {
	  var categories = db.Categories.Include(c => c.Type);
	  return View(await categories.ToListAsync());
	}

	// GET: Categories/Details/5
	public async Task<ActionResult> Details(int? id) {
	  if (id == null) {
		return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
	  }
	  Category category = await db.Categories.FindAsync(id);
	  if (category == null) {
		return HttpNotFound();
	  }
	  return View(category);
	}

	// GET: Categories/Create
	public ActionResult Create() {
	  ViewBag.CategoryId = new SelectList(db.Types, "TypeId", "Description");
	  return View();
	}

	// POST: Categories/Create
	// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
	// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<ActionResult> Create([Bind(Include = "CategoryId,Description,Enabled,Deleted")] Category category) {
	  if (ModelState.IsValid) {
		db.Categories.Add(category);
		await db.SaveChangesAsync();
		return RedirectToAction("Index");
	  }

	  ViewBag.CategoryId = new SelectList(db.Types, "TypeId", "Description", category.CategoryId);
	  return View(category);
	}

	// GET: Categories/Edit/5
	public async Task<ActionResult> Edit(int? id) {
	  if (id == null) {
		return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
	  }
	  Category category = await db.Categories.FindAsync(id);
	  if (category == null) {
		return HttpNotFound();
	  }
	  ViewBag.CategoryId = new SelectList(db.Types, "TypeId", "Description", category.CategoryId);
	  return View(category);
	}

	// POST: Categories/Edit/5
	// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
	// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<ActionResult> Edit([Bind(Include = "CategoryId,Description,Enabled,Deleted")] Category category) {
	  if (ModelState.IsValid) {
		db.Entry(category).State = EntityState.Modified;
		await db.SaveChangesAsync();
		return RedirectToAction("Index");
	  }
	  ViewBag.CategoryId = new SelectList(db.Types, "TypeId", "Description", category.CategoryId);
	  return View(category);
	}

	// GET: Categories/Delete/5
	public async Task<ActionResult> Delete(int? id) {
	  if (id == null) {
		return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
	  }
	  Category category = await db.Categories.FindAsync(id);
	  if (category == null) {
		return HttpNotFound();
	  }
	  return View(category);
	}

	// POST: Categories/Delete/5
	[HttpPost, ActionName("Delete")]
	[ValidateAntiForgeryToken]
	public async Task<ActionResult> DeleteConfirmed(int id) {
	  Category category = await db.Categories.FindAsync(id);
	  db.Categories.Remove(category);
	  await db.SaveChangesAsync();
	  return RedirectToAction("Index");
	}

	protected override void Dispose(bool disposing) {
	  if (disposing) {
		db.Dispose();
	  }
	  base.Dispose(disposing);
	}
  }
}

SIGEAO/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        Desarrollado por <a target="_blank" href="http://www.key-core.com"><img height="25" src="~/Content/Styles/dist/img/LogoGris.png" /></a>
    </div>
    <div>
        <strong>SIGEAO</strong> &copy; 2017. Todos los derechos reservados
    </div>
</div>

SIGEAO/Views/Shared/_Header.cshtml
<div class="row border-bottom">
	 <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
	 	 <div class="navbar-header">
	 	 	 <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
	 	 	 <form role="search" class="navbar-form-custom" action="http://webapplayers.com/inspinia_admin-v2.7.1/search_results.html">
	 	 	 	 <div class="form-group">
	 	 	 	 	 <input type="text" placeholder="Buscar..." class="form-control" name="top-search" id="top-search">
	 	 	 	 </div>
	 	 	 </form>
	 	 </div>
	 	 <ul class="nav navbar-top-links navbar-right">
	 	 	 <li>
	 	 	 	 <span class="m-r-sm text-muted welcome-message">Bienvenido a SIGEAO...</span>
	 	 	 </li>
	 	 	 <li class="dropdown">
	 	 	 	 <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
	 	 	 	 	 <i class="fa fa-bell"></i>  <span class="label label-danger">2</span>
	 	 	 	 </a>
	 	 	 	 <ul class="dropdown-menu dropdown-alerts">
	 	 	 	 	 <li>
	 	 	 	 	 	 <a href="">
	 	 	 	 	 	 	 <div>
	 	 	 	 	 	 	 	 <i class="fa fa-check-square-o fa-fw"></i> Tienes 2 Solicitudes por Aprobar
	 	 	 	 	 	 	 	 <span class="pull-right text-muted small">2 dias</span>
	 	 	 	 	 	 	 </div>
	 	 	 	 	 	 </a>
	 	 	 	 	 </li>

	 	 	 	 	 <li class="divider"></li>
	 	 	 	 	 <li>
	 	 	 	 	 	 <div class="text-center link-block">
	 	 	 	 	 	 	 <a href="#">
	 	 	 	 	 	 	 	 <strong>Ver Todas</strong>
	 	 	 	 	 	 	 	 <i class="fa fa-angle-right"></i>
	 	 	 	 	 	 	 </a>
	 	 	 	 	 	 </div>
	 	 	 	 	 </li>
	 	 	 	 </ul>
	 	 	 </li>
	 	 	 <li>
	 	 	 	 @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" })) {
	 	 	 	 	 @Html.AntiForgeryToken()
	 	 	 	 <a href="javascript:document.getElementById('logoutForm').submit()" class="btn">
	 	 	 	 	 <i class="fa fa-sign-out"></i>
	 	 	 	 	 Salir
	 	 	 	 </a>
				}
	 	 </li>
	 </ul>

</nav>
</div>

SIGEAO/Views/Shared/_HeaderContent.cshtml
@model SIGEAO.Models.ViewModels.IViewModel

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@Model.TitleView</h2>
    </div>
    <div class="col-lg-2"></div>
</div>

SIGEAO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewBag.Title - SIGEAO</title>
    <link rel="shortcut icon" type="image/png" href="~/Content/Styles/dist/img/logo-credipronto-[Convertido2].png" />

    @Styles.Render("~/BootstrapCSS")
    @Styles.Render("~/Jasny")
    @Styles.Render("~/AwesomeBootstrapCheckbox")
    @Styles.Render("~/Touchspin")
    @Styles.Render("~/ICheck")
    @Styles.Render("~/InspiniaCSS")

    @Scripts.Render("~/Modernizr")

</head>
<body class="skin-1">
		<div id="wrapper">
				@Html.Partial("_Navbar")
				<div id="page-wrapper" class="gray-bg">
						@Html.Partial("_Header")
						@RenderSection("Navegacion", required: false)
						@RenderBody()
						<br />
						<br />
						@Html.Partial("_Footer")
				</div>
		</div>


		@Scripts.Render("~/JQuery")
		@Scripts.Render("~/BootstrapJS")
		@Scripts.Render("~/MetisMenu")
		@Scripts.Render("~/SlimScroll")
		@Scripts.Render("~/InspiniaJS")
		@Scripts.Render("~/Pace")

		@RenderSection("scripts", required: false)

</body>
</html>

SIGEAO/Views/Shared/_Navbar.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
				<ul class="nav metismenu" id="side-menu">
						<li class="nav-header">
								<div class="dropdown profile-element">
										<span>
												<img alt="image" class="img-circle" src="~/Content/Styles/dist/img/profile_small.jpg" />
										</span>
										<a data-toggle="dropdown" class="dropdown-toggle" href="#">
												<span class="clear">
														<span class="block m-t-xs">
																<strong class="font-bold">Nombre Pila</strong>
														</span> <span class="text-muted text-xs block">Rol Usuario<b class="caret"></b></span>
												</span>
										</a>
										<ul class="dropdown-menu animated fadeInRight m-t-xs">
												<li><a href="">Perfil</a></li>
												<li class="divider"></li>
												<li><a href="">Salir</a></li>
										</ul>
								</div>
								<div class="logo-element">
										SIGEAO
								</div>
						</li>
						<li>
								<a href="index-2.html"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span> <span class="fa arrow"></span></a>
								<ul class="nav nav-second-level collapse">
										<li><a href="">Dashboard v.1</a></li>
										@*<li><a href="dashboard_2.html">Dashboard v.2</a></li>
								<li><a href="dashboard_3.html">Dashboard v.3</a></li>
								<li><a href="dashboard_4_1.html">Dashboard v.4</a></li>
								<li><a href="dashboard_5.html">Dashboard v.5 </a></li>*@
								</ul>
						</li>
						<li>
								<a href="@Url.Action("Index", "Categories")"><i class="fa fa-cogs"></i> <span class="nav-label">Categorias</span>  </a>
						</li>
						<li>
								<a href="#"><i class="fa fa-cogs"></i> <span class="nav-label">Administraci&oacute;n</span><span class="fa arrow"></span></a>
								<ul class="nav nav-second-level collapse">
										<li><a href="@Url.Action("Lista", "Accion")"><i class="fa fa-cog"></i>Acciones</a></li>
										<li><a href="@Url.Action("Lista", "Banco")"><i class="fa fa-bank"></i>Bancos</a></li>
										<li><a href="@Url.Action("Lista", "Bandera")"><i class="fa fa-flag"></i>Banderas</a></li>
										<li><a href="@Url.Action("Lista", "Cargo")"><i class="fa fa-user-o"></i>Cargos</a></li>
										<li><a href="@Url.Action("Lista", "ConceptoGasto")"><i class="fa fa-money"></i>Conceptos de Gastos</a></li>
										<li><a href="@Url.Action("Lista", "EstadoCivil")"><i class="fa fa-heart"></i>Estados Civiles</a></li>
										<li><a href="@Url.Action("Lista", "Estatus")"><i class="fa fa-arrows-alt"></i>Estatus</a></li>
										<li><a href="@Url.Action("Lista", "Inversionista")"><i class="fa fa-black-tie"></i>Inversionistas</a></li>
										<li><a href="@Url.Action("Lista", "LineaComision")"><i class="fa fa-percent"></i>L&iacute;neas de Comisi&oacute;n</a></li>
										<li><a href="@Url.Action("Lista", "LineaCredito")"><i class="fa fa-credit-card"></i>L&iacute;neas de Cr&eacute;dito</a></li>
										<li><a href="@Url.Action("Lista", "MotivoRechazo")"><i class="fa fa-times"></i>Motivos de rechazo</a></li>
										<li><a href="@Url.Action("Lista", "Oficina")"><i class="fa fa-institution"></i>Oficina</a></li>
										<li><a href="@Url.Action("Editar", "Parametros")"><i class="fa fa-wrench"></i>Par&aacute;metros</a></li>
										<li><a href="@Url.Action("Lista", "Parentesco")"><i class="fa fa-users"></i>Parentesco</a></li>
										<li><a href="@Url.Action("Lista", "TipoCuenta")"><i class="fa fa-credit-card-alt"></i>Tipos de Cuentas</a></li>
										<li><a href="@Url.Action("Lista", "TipoDocumento")"><i class="fa fa-id-card"></i>Tipos de Documentos</a></li>
										<li><a href="@Url.Action("Lista", "TipoInmueble")"><i class="fa fa-building"></i>Tipos de Inmuebles</a></li>
										<li><a href="@Url.Action("Lista", "TipoMovimiento")"><i class="fa fa-arrows-h"></i>Tipos de Movimientos</a></li>
										<li><a href="@Url.Action("Lista", "Transacciones")"><i class="fa fa-arrows-h"></i>Log de Transacciones</a></li>
										<li><a href="@Url.Action("Lista", "Ubicacion")"><i class="fa fa-globe"></i>Ubicaci&oacute;n Geogr&aacute;fica</a></li>
								</ul>
						</li>
						<li>
								<a href="#"><i class="fa fa-book"></i> <span class="nav-label">Solicitudes</span><span class="fa arrow"></span></a>
								<ul class="nav nav-second-level collapse">
										<li><a href="@Url.Action("Lista", "Solicitud")"><i class="fa fa-file"></i>Lista</a></li>
										<li><a href="@Url.Action("Crear", "Solicitud")"><i class="fa fa-spin fa-spinner"></i>Nueva</a></li>
										<li><a href=""><i class="fa fa-check-circle-o"></i>Aprobadas</a></li>
										<li><a href=""><i class="fa fa-times-rectangle"></i>Rechazadas</a></li>
										<li><a href=""><i class="fa fa-eye"></i>Peritaje</a></li>
								</ul>
						</li>
						<li>
								<a href=""><i class="fa fa-credit-card"></i> <span class="nav-label">Créditos </span><span class="fa arrow"></span></a>
								<ul class="nav nav-second-level collapse">
										<li><a href="@Url.Action("Lista", "Credito")"><i class="fa fa-file"></i>Lista</a></li>
								</ul>
						</li>
						<li>
								<a href="@Url.Action("Simulador", "Solicitud")"><i class="fa fa-calculator"></i> <span class="nav-label">Simulador</span>  </a>
						</li>
						<li>
								<a href="@Url.Action("Index", "Appointment")"><i class="fa fa-sign-in"></i> <span class="nav-label">Citas</span>  </a>
						</li>

				</ul>
    </div>
</nav>

SIGEAO/Views/Shared/_Persona.cshtml
@model CrediPronto.Interface.IPersona
@*DATOS PERSONALES*@
<div class="row">
    <div class="col-lg-12">
        <div class="ibox">
            <div class="ibox-title">
                <h5><i class="fa fa-user"></i>&nbsp;&nbsp;Datos Personales</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                @Html.HiddenFor(m => m.ID_Persona)
                <div class="row">
                    <div class="form-group col-lg-3 col-md-4 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.ID_TipoDocumento)
                        @Html.DropDownListFor(m => m.ID_TipoDocumento, new SelectList(Model.ListaTipoDocumento, "ID_TipoDocumento", "TX_TipoDocumento"), "", new { @class = "form-control" })
                        @*@Html.ValidationMessageFor(m=> m.ID_TipoDocumento, "", new { @class = "text-danger" })*@
                    </div>
                    <div class="form-group col-lg-3 col-md-4 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.NU_Documento)
                        @Html.TextBoxFor(m => m.NU_Documento, new { @class = "form-control quitarFlechasInputNumerico", @type = "number" })
                        @*@Html.ValidationMessageFor(m => m.NU_Documento, "", new { @class = "text-danger" })*@
                    </div>
                    <div class="form-group col-lg-3 col-md-4 col-sm-12 col-xs-12 espacio-top-25">
                        <button class="btn btn-success" type="button" id="btnBuscar">
                            <i class="fa fa-search"></i>&nbsp;&nbsp;<span class="bold">Buscar</span>
                        </button>
                    </div>
                    <div class="form-group col-lg-3 col-md-4 col-sm-12 col-xs-12">
                        <div class="spiner-example espacio-top-25" id="spiner-buscarPersona" style="height:60px;">
                            <div class="sk-spinner sk-spinner-rotating-plane"></div>
                        </div>
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="row">
                    <div class="form-group col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_Nombre1)
                        @Html.TextBoxFor(m => m.TX_Nombre1, new { @class = "form-control" })
                        @*@Html.ValidationMessageFor(m => m.TX_Nombre1, "", new { @class = "text-danger" })*@
                    </div>
                    <div class="form-group col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_Nombre2)
                        @Html.TextBoxFor(m => m.TX_Nombre2, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_Apellido1)
                        @Html.TextBoxFor(m => m.TX_Apellido1, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_Apellido2)
                        @Html.TextBoxFor(m => m.TX_Apellido2, new { @class = "form-control" })
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="row">
                    <div class="form-group col-lg-3 col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group" id="txtFechaNacimiento">
                            @Html.LabelFor(m => m.DT_FechaNacimientoString)
                            <div class="input-group date">
                                <span class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </span>
                                @Html.TextBoxFor(m => m.DT_FechaNacimientoString, new { @class = "form-control sed" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-lg-3 col-md-6 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.ID_EstadoCivil)
                        @Html.DropDownListFor(m => m.ID_EstadoCivil, new SelectList(Model.CP_ESTADO_CIVIL, "ID_EstadoCivil", "TX_EstadoCivil"), "", new { @class = "form-control" })
                    </div>
                  
                </div>
                <div class="row">
                    <div class="form-group col-lg-3 col-md-6 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_TelefonoFijo)
                        <div class="input-group m-b">
                            <span class="input-group-addon">
                                <i class="fa fa-phone"></i>
                            </span>
                            @Html.TextBoxFor(m => m.TX_TelefonoFijo, new { @class = "form-control maskPhone", placeholder = "" })
                        </div>
                    </div>
                    <div class="form-group col-lg-3 col-md-6 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_TelefonoCelular)
                        <div class="input-group m-b">
                            <span class="input-group-addon">
                                <i class="fa fa-mobile-phone"></i>
                            </span>
                            @Html.TextBoxFor(m => m.TX_TelefonoCelular, new { @class = "form-control maskPhone", placeholder = "" })
                        </div>
                    </div>
                    <div class="form-group col-lg-3 col-md-6 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_CorreoElectronico)
                        <div class="input-group m-b">
                            <span class="input-group-addon">@@</span>
                            @Html.TextBoxFor(m => m.TX_CorreoElectronico, new { @class = "form-control", @type = "email" })
                        </div>
                    </div>
                </div>
                    <div class="hr-line-dashed"></div>
                    <div class="row">
                        <div class="form-group col-lg-3 col-md-4 col-sm-12 col-xs-12">
                            @Html.LabelFor(m => m.ID_Pais_Casa)
                            @Html.DropDownListFor(m => m.ID_Pais_Casa, new SelectList(Model.CP_PAIS_CASA, "ID_Pais", "TX_Pais"), "", new { @class = "form-control" })
                        </div>
                        <div class="form-group col-lg-3 col-md-4 col-sm-12 col-xs-12">
                            @Html.LabelFor(m => m.ID_Departamento_Casa)
                            @Html.DropDownListFor(m => m.ID_Departamento_Casa, new SelectList(Model.CP_DEPARTAMENTO_CASA, "ID_Departamento", "TX_Departamento"), "", new { @class = "form-control chosen-select", data_placeholder = "Departamento..." })
                        </div>
                        <div class="form-group col-lg-3 col-md-4 col-sm-12 col-xs-12">
                            @Html.LabelFor(m => m.ID_Municipio_Casa)
                            @Html.DropDownListFor(m => m.ID_Municipio_Casa, new SelectList(Model.CP_MUNICIPIO_CASA, "ID_Municipio", "TX_Municipio"), "", new { @class = "form-control chosen-select", data_placeholder = "Municipio..." })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            @Html.LabelFor(m => m.TX_BarrioCasa)
                            @Html.TextAreaFor(m => m.TX_BarrioCasa, new { @class = "form-control" })
                        </div>
                        <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            @Html.LabelFor(m => m.TX_DireccionCasa)
                            @Html.TextAreaFor(m => m.TX_DireccionCasa, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="row">
                        <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            @Html.LabelFor(m => m.IM_Fotografia)
                            <br />
                            <output id="outLogo"></output>
                            <div class="attachment-block clearfix">
                                <img id="fotoConvertida" class="img-responsive" src="@Model.FotoConvertida">
                            </div>
                            <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                <div class="form-control" data-trigger="fileinput">
                                    <i class="glyphicon glyphicon-file fileinput-exists"></i>
                                    <span class="fileinput-filename"></span>
                                </div>
                                <span class="input-group-addon btn btn-default btn-file">
                                    <span class="fileinput-new">Seleccionar archivo</span>
                                    <span class="fileinput-exists">Cambiar</span>
                                    <input type="file" name="fotoPost" id="fotoPost" accept="image/jpeg,image/gif,image/png" />
                                </span>
                                <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Eliminar</a>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</div>
@*DATOS LABORALES*@
<div class="row">
    <div class="col-lg-12">
        <div class="ibox">
            <div class="ibox-title">
                <h5><i class="fa fa-institution"></i>&nbsp;&nbsp;Datos Laborales</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="row">
                    <div class="form-group col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_Empresa)
                        @Html.TextBoxFor(m => m.TX_Empresa, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_Cargo)
                        @Html.TextBoxFor(m => m.TX_Cargo, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_TiempoServicio)
                        @Html.TextBoxFor(m => m.TX_TiempoServicio, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_TelefonoOficina)
                        <div class="input-group m-b">
                            <span class="input-group-addon">
                                <i class="fa fa-phone"></i>
                            </span>
                            @Html.TextBoxFor(m => m.TX_TelefonoOficina, new { @class = "form-control maskPhone", placeholder = "" })
                        </div>
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="row">
                    <div class="form-group col-lg-3 col-md-4 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.ID_Pais_Empresa)
                        @Html.DropDownListFor(m => m.ID_Pais_Empresa, new SelectList(Model.CP_PAIS_EMPRESA, "ID_Pais", "TX_Pais"), "", new { @class = "form-control" })
                    </div>
                    <div class="form-group col-lg-3 col-md-4 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.ID_Departamento_Empresa)
                        @Html.DropDownListFor(m => m.ID_Departamento_Empresa, new SelectList(Model.CP_DEPARTAMENTO_EMPRESA, "ID_Departamento", "TX_Departamento"), "", new { @class = "form-control chosen-select", data_placeholder = "Departamento..." })
                    </div>
                    <div class="form-group col-lg-3 col-md-4 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.ID_Municipio_Empresa)
                        @Html.DropDownListFor(m => m.ID_Municipio_Empresa, new SelectList(Model.CP_MUNICIPIO_EMPRESA, "ID_Municipio", "TX_Municipio"), "", new { @class = "form-control chosen-select", data_placeholder = "Municipio..." })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_BarrioEmpresa)
                        @Html.TextAreaFor(m => m.TX_BarrioEmpresa, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        @Html.LabelFor(m => m.TX_DireccionEmpresa)
                        @Html.TextAreaFor(m => m.TX_DireccionEmpresa, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>